name: Update Action Versions

on:
  schedule:
    - cron: '0 8 * * *' # every day at 8AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Ensure docs folder exists
        run: mkdir -p docs

      - name: Generate Markdown file with release notes, avatars, and links
        run: |
          #!/bin/bash
          set -e

          ACTIONS=(
            "actions/checkout"
            "actions/setup-java"
            "actions/setup-python"
            "actions/setup-dotnet"
            "actions/setup-node"
            "actions/upload-artifact"
            "actions/download-artifact"
            "actions/github-script"
            "actions/stale"
          )

          echo "# GitHub Actions Versions" > docs/index.md
          echo "" >> docs/index.md

          for repo in "${ACTIONS[@]}"; do
            echo "## $repo" >> docs/index.md
            echo "" >> docs/index.md
            echo "| Major | Version | Release Date | Link |" >> docs/index.md
            echo "|-------|---------|-------------|------|" >> docs/index.md

            releases=$(curl -s "https://api.github.com/repos/$repo/releases")
            tags=$(echo "$releases" | jq -r '.[].tag_name' | grep -E '^v[0-9]+(\.[0-9]+)*$')
            majors=$(echo "$tags" | grep -o '^v[0-9]\+' | sort -Vr | uniq | head -n 2)

            # Collect release data
            declare -a rel_table_rows=()
            declare -a rel_details_blocks=()

            for major in $majors; do
              # Get all releases for this major, sorted by version (descending)
              major_releases=$(echo "$releases" | jq -c ".[] | select(.tag_name|startswith(\"$major.\"))")
              if [[ -z "$major_releases" ]]; then
                # Fallback: check for releases with tag exactly matching the major version
                major_releases=$(echo "$releases" | jq -c ".[] | select(.tag_name==\"$major\")")
              fi

              # Table rows
              echo "$major_releases" | jq -c '.' | while read -r rel; do
                tag=$(echo "$rel" | jq -r '.tag_name')
                date=$(echo "$rel" | jq -r '.published_at' | cut -d'T' -f1)
                url=$(echo "$rel" | jq -r '.html_url')
                rel_table_rows+=("| $major | $tag | $date | [View Release]($url) |")
              done

              # Details blocks
              echo "$major_releases" | jq -c '.' | while read -r rel; do
                tag=$(echo "$rel" | jq -r '.tag_name')
                notes=$(echo "$rel" | jq -r '.body // "No release notes."')
                author_login=$(echo "$rel" | jq -r '.author.login')
                author_avatar=$(echo "$rel" | jq -r '.author.avatar_url')
                url=$(echo "$rel" | jq -r '.html_url')
                rel_details_blocks+=("<details><summary><strong>$tag Release Notes</strong></summary>
<img src=\"$author_avatar\" alt=\"@$author_login\" width=\"32\" height=\"32\" /> <a href=\"https://github.com/$author_login\">@$author_login</a>
<br />
$notes
<br />
<a href=\"$url\">View Release</a>
</details>
")
              done
            done

            # Print table rows
            for row in "${rel_table_rows[@]}"; do
              echo "$row" >> docs/index.md
            done

            echo "" >> docs/index.md

            # Print details blocks
            for block in "${rel_details_blocks[@]}"; do
              echo "$block" >> docs/index.md
              echo "" >> docs/index.md
            done

            unset rel_table_rows
            unset rel_details_blocks
          done

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # Store a PAT as GH_TOKEN
        run: |
          git config --global user.email "workflow-bot@github.com"
          git config --global user.name "Workflow Bot"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git add docs/index.md
          git commit -m "Update action versions [skip ci]" || exit 0
          git push