name: Update Action Versions

on:
  schedule:
    - cron: '0 8 * * *' # every day at 8AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
    
      - name: Ensure docs folder exists
        run: mkdir -p docs

      - name: Fetch tags for actions/checkout
        run: |
          curl -s https://api.github.com/repos/actions/checkout/tags | jq -r '.[].name' > tags.txt

      - name: Generate Markdown file
        run: |
          #!/bin/bash

          set -e

          # List of actions to check (add more as needed)
          ACTIONS=(
            "actions/checkout"
            "actions/setup-java"
            "actions/setup-python"
            "actions/setup-dotnet"
            "actions/setup-node"
            "actions/upload-artifact"
            "actions/download-artifact"
            "actions/toolkit"
            "actions/github-script"
            "actions/stale"
          )

          echo "# GitHub Actions Versions" > docs/index.md
          echo "" >> docs/index.md

          for repo in "${ACTIONS[@]}"; do
            echo "## $repo" >> docs/index.md
            echo "" >> docs/index.md
            echo "| Major | Latest Minor/Patch |" >> docs/index.md
            echo "|-------|--------------------|" >> docs/index.md

            tags=$(curl -s "https://api.github.com/repos/$repo/tags" | jq -r '.[].name' | grep -E '^v[0-9]+(\.[0-9]+)*$')

            # Get major versions (v4, v5, etc.)
            majors=$(echo "$tags" | grep -o '^v[0-9]\+' | sort -Vr | uniq)
            majors=$(echo "$majors" | head -n 2) # get latest 2 major versions

            for major in $majors; do
              # Get all tags for this major, sort, pick latest
              latest=$(echo "$tags" | grep "^$major" | sort -Vr | head -n 1)
              echo "| $major | $latest |" >> docs/index.md
            done

            echo "" >> docs/index.md
          done
      - name: Commit and push changes
        run: |
          git config --global user.email "workflow-bot@github.com"
          git config --global user.name "Workflow Bot"
          git add docs/index.md
          git commit -m "Update action versions [skip ci]" || exit 0
          git push
