name: Update Action Versions

on:
  schedule:
    - cron: '0 8 * * *' # every day at 8AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Ensure docs folder exists
        run: mkdir -p docs

      - name: Generate Markdown file with sorted repos, TOC, release notes, avatars, and links
        run: |
          #!/bin/bash
          set -e

          # Robust prettify_notes function
          prettify_notes() {
            local notes="$1"
            # If notes are empty, just return
            if [[ -z "$notes" ]]; then
              echo "No release notes."
              return
            fi
            set +e
            notes=$(echo "$notes" | sed -E 's/@([a-zA-Z0-9_-]+)/[@\1](https:\/\/github.com\/\1)/g')
            notes=$(echo "$notes" | sed -E 's#(https://github.com/[^ ]+/pull/[0-9]+)# [PR](\1)#g')
            notes=$(echo "$notes" | sed -E 's#(https://github.com/[^ ]+/issues/[0-9]+)# [Issue](\1)#g')
            notes=$(echo "$notes" | sed -E 's/\* /\n- /g')
            notes=$(echo "$notes" | sed -E 's/^(#+)/\n\1/g')
            set -e
            echo "$notes"
          }

          # Alphabetically sorted repo list
          ACTIONS=(
            "actions/add-to-project"
            "actions/attest"
            "actions/attest-build-provenance"
            "actions/attest-sbom"
            "actions/cache"
            "actions/checkout"
            "actions/configure-pages"
            "actions/create-github-app-token"
            "actions/dependency-review-action"
            "actions/deploy-pages"
            "actions/delete-package-versions"
            "actions/download-artifact"
            "actions/first-interaction"
            "actions/github-script"
            "actions/go-dependency-submission"
            "actions/hello-world-javascript-action"
            "actions/javascript-action"
            "actions/runner"
            "actions/setup-dotnet"
            "actions/setup-go"
            "actions/setup-java"
            "actions/setup-node"
            "actions/setup-python"
            "actions/stale"
            "actions/starter-workflows"
            "actions/toolkit"
            "actions/upload-artifact"
          )

          echo "# GitHub Actions Versions" > docs/index.md
          echo "" >> docs/index.md

          # Table of Contents
          echo "## Table of Contents" >> docs/index.md
          for repo in "${ACTIONS[@]}"; do
            anchor=$(echo "$repo" | tr '/' '-' | tr '[:upper:]' '[:lower:]')
            echo "- [${repo}](#${anchor})" >> docs/index.md
          done
          echo "" >> docs/index.md

          # Output sections in alphabetical order
          for repo in "${ACTIONS[@]}"; do
            anchor=$(echo "$repo" | tr '/' '-' | tr '[:upper:]' '[:lower:]')
            echo "## $repo" >> docs/index.md
            echo "<a name=\"$anchor\"></a>" >> docs/index.md
            echo "" >> docs/index.md
            echo "| Major | Version | Release Date | Link |" >> docs/index.md
            echo "|-------|---------|-------------|------|" >> docs/index.md

            releases=$(curl -s "https://api.github.com/repos/$repo/releases")
            if ! echo "$releases" | jq empty > /dev/null 2>&1; then
              echo "| No releases found | | | |" >> docs/index.md
              continue
            fi

            tags=$(echo "$releases" | jq -r '.[].tag_name' | grep -E '^v[0-9]+(\.[0-9]+)*$')
            if [[ -z "$tags" ]]; then
              echo "| No tags found | | | |" >> docs/index.md
              continue
            fi

            majors=$(echo "$tags" | grep -o '^v[0-9]\+' | sort -Vr | uniq | head -n 2)

            # Table rows
            for major in $majors; do
              major_releases=$(echo "$releases" | jq -c ".[] | select(.tag_name|startswith(\"$major.\"))")
              if [[ -z "$major_releases" ]]; then
                major_releases=$(echo "$releases" | jq -c ".[] | select(.tag_name==\"$major\")")
              fi
              echo "$major_releases" | jq -c '.' | while read -r rel; do
                tag=$(echo "$rel" | jq -r '.tag_name')
                date=$(echo "$rel" | jq -r '.published_at' | cut -d'T' -f1)
                url=$(echo "$rel" | jq -r '.html_url')
                echo "| $major | $tag | $date | [View Release]($url) |" >> docs/index.md
              done
            done

            echo "" >> docs/index.md

            # Release details
            for major in $majors; do
              major_releases=$(echo "$releases" | jq -c ".[] | select(.tag_name|startswith(\"$major.\"))")
              if [[ -z "$major_releases" ]]; then
                major_releases=$(echo "$releases" | jq -c ".[] | select(.tag_name==\"$major\")")
              fi
              echo "$major_releases" | jq -c '.' | while read -r rel; do
                tag=$(echo "$rel" | jq -r '.tag_name')
                notes=$(echo "$rel" | jq -r '.body // ""')
                if [[ -z "$notes" ]]; then
                  notes="No release notes."
                else
                  notes=$(prettify_notes "$notes")
                fi
                author_login=$(echo "$rel" | jq -r '.author.login')
                author_avatar=$(echo "$rel" | jq -r '.author.avatar_url')
                url=$(echo "$rel" | jq -r '.html_url')
                echo "<details><summary><strong>$tag Release Notes</strong></summary>" >> docs/index.md
                echo "<img src=\"$author_avatar\" alt=\"@$author_login\" width=\"32\" height=\"32\" /> <a href=\"https://github.com/$author_login\">@$author_login</a>" >> docs/index.md
                echo "" >> docs/index.md
                echo "$notes" >> docs/index.md
                echo "<br /><a href=\"$url\">View Release</a>" >> docs/index.md
                echo "</details>" >> docs/index.md
                echo "" >> docs/index.md
              done
            done

            echo "" >> docs/index.md
          done

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "workflow-bot@github.com"
          git config --global user.name "Workflow Bot"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git add docs/index.md
          git commit -m "Update action versions [skip ci]" || exit 0
          git push